In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

In [2]:
df_adopciones = pd.read_csv("../data/Raw/pet_adoption_data.csv")

### Visualización general de los datos

In [3]:
df_adopciones.head()

,PetID,PetType,Breed,AgeMonths,Color,Size,WeightKg,Vaccinated,HealthCondition,TimeInShelterDays,AdoptionFee,PreviousOwner,AdoptionLikelihood
0,500,Bird,Parakeet,131,Orange,Large,5.039768,1,0,27,140,0,0
1,501,Rabbit,Rabbit,73,White,Large,16.086727,0,0,8,235,0,0
2,502,Dog,Golden Retriever,136,Orange,Medium,2.076286,0,0,85,385,0,0
3,503,Bird,Parakeet,97,White,Small,3.339423,0,0,61,217,1,0
4,504,Rabbit,Rabbit,123,Gray,Large,20.498100,0,0,28,14,1,0

In [4]:
df_adopciones.describe()

,PetID,AgeMonths,WeightKg,Vaccinated,HealthCondition,TimeInShelterDays,AdoptionFee,PreviousOwner,AdoptionLikelihood
count,2007.000000,2007.000000,2007.000000,2007.000000,2007.000000,2007.000000,2007.000000,2007.000000,2007.000000
mean,1503.000000,92.279522,15.705776,0.701046,0.196313,43.974091,249.142003,0.301943,0.328351
std,579.515315,52.148363,8.327749,0.457914,0.397307,25.740253,142.887040,0.459215,0.469730
min,500.000000,1.000000,1.018198,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,1001.500000,48.000000,8.730396,0.000000,0.000000,21.000000,127.000000,0.000000,0.000000
50%,1503.000000,94.000000,15.925416,1.000000,0.000000,45.000000,242.000000,0.000000,0.000000
75%,2004.500000,138.000000,22.737180,1.000000,0.000000,66.000000,375.000000,1.000000,1.000000
max,2506.000000,179.000000,29.995628,1.000000,1.000000,89.000000,499.000000,1.000000,1.000000

In [5]:
df_adopciones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2007 entries, 0 to 2006
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   PetID               2007 non-null   int64
 1   PetType             2007 non-null   object
 2   Breed               2007 non-null   object
 3   AgeMonths           2007 non-null   int64
 4   Color               2007 non-null   object
 5   Size                2007 non-null   object
 6   WeightKg            2007 non-null   float64
 7   Vaccinated          2007 non-null   int64
 8   HealthCondition     2007 non-null   int64
 9   TimeInShelterDays   2007 non-null   int64
 10  AdoptionFee         2007 non-null   int64
 11  PreviousOwner       2007 non-null   int64
 12  AdoptionLikelihood  2007 non-null   int64
dtypes: float64(1), int64(8), object(4)
memory usage: 204.0+ KB

### Preparación y limpieza de datos

- En el caso de la variable PetID (Identificador del animal) no es necesaria para la predicción. Por lo que esa variable va a ser eliminada.  
- Creo que para una mejor interpretación y comprensión de los datos en la presentación, es necesario cambiar las edades de meses a años.  
- Para manipular mejor la variable target, voy a cambiarle el nombre de "AdoptionLikelihood" a "target"

In [6]:
train, test = train_test_split(df_adopciones, test_size=0.2, stratify=df_adopciones['AdoptionLikelihood'], random_state=42)

In [7]:
# Elimino PetID:

train = train.drop(columns = ["PetID"], axis = 1)
test = test.drop(columns = ["PetID"], axis = 1)

In [8]:
# Transformación de edad de meses a años:

train["AgeYears"] = round(df_adopciones["AgeMonths"]/12, 2)
test["AgeYears"] = round(df_adopciones["AgeMonths"]/12, 2)

In [9]:
# Elimino columna de AgeMonths

train = train.drop(columns = ["AgeMonths"], axis = 1)
test = test.drop(columns = ["AgeMonths"], axis = 1)

In [10]:
# Cambio nombre de target

train = train.rename(columns = {"AdoptionLikelihood": "target"})
test = test.rename(columns = {"AdoptionLikelihood": "target"})

In [11]:
train.to_csv('../data/Raw/train_data_raw.csv', index = False)
train.head()

,PetType,Breed,Color,Size,WeightKg,Vaccinated,HealthCondition,TimeInShelterDays,AdoptionFee,PreviousOwner,target,AgeYears
1614,Cat,Siamese,White,Large,7.489573,0,0,70,476,0,0,14.33
1986,Bird,Parakeet,White,Medium,23.903091,1,0,85,437,0,0,12.33
1073,Dog,Poodle,Gray,Large,26.039470,1,0,52,451,0,0,7.75
1721,Cat,Persian,White,Large,17.110227,0,0,6,298,0,0,8.83
883,Cat,Siamese,White,Medium,10.598766,1,0,27,10,0,1,7.42

##### Datos limpios:

- Columna PetID eliminada
- Transformación de edad de meses a años
- Cambio de nombre de la variable target

El dataset original no tiene valores nulos, por lo que no tengo que realizar ninguna imputación de valores

In [12]:
train.head()

,PetType,Breed,Color,Size,WeightKg,Vaccinated,HealthCondition,TimeInShelterDays,AdoptionFee,PreviousOwner,target,AgeYears
1614,Cat,Siamese,White,Large,7.489573,0,0,70,476,0,0,14.33
1986,Bird,Parakeet,White,Medium,23.903091,1,0,85,437,0,0,12.33
1073,Dog,Poodle,Gray,Large,26.039470,1,0,52,451,0,0,7.75
1721,Cat,Persian,White,Large,17.110227,0,0,6,298,0,0,8.83
883,Cat,Siamese,White,Medium,10.598766,1,0,27,10,0,1,7.42

In [13]:
features = train.columns.to_list()

In [14]:
# Transformación de las variables:

train = pd.get_dummies(train[features], columns = ["PetType", "Breed", "Color", "Size"], dtype = int)
test = pd.get_dummies(test[features], columns = ["PetType", "Breed", "Color", "Size"], dtype = int)

In [15]:
train.to_csv('../data/Clean/train_data_clean.csv', index = False)
test.to_csv('../data/Clean/test_data_clean.csv', index = False)

In [16]:
train.head()

,WeightKg,Vaccinated,HealthCondition,TimeInShelterDays,AdoptionFee,PreviousOwner,target,AgeYears,PetType_Bird,PetType_Cat,...,Breed_Rabbit,Breed_Siamese,Color_Black,Color_Brown,Color_Gray,Color_Orange,Color_White,Size_Large,Size_Medium,Size_Small
1614,7.489573,0,0,70,476,0,0,14.33,0,1,...,0,1,0,0,0,0,1,1,0,0
1986,23.903091,1,0,85,437,0,0,12.33,1,0,...,0,0,0,0,0,0,1,0,1,0
1073,26.039470,1,0,52,451,0,0,7.75,0,0,...,0,0,0,0,1,0,0,1,0,0
1721,17.110227,0,0,6,298,0,0,8.83,0,1,...,0,0,0,0,0,0,1,1,0,0
883,10.598766,1,0,27,10,0,1,7.42,0,1,...,0,1,0,0,0,0,1,0,1,0